box-forced deprecated in matplotlib
When adding more than one Hi-C map in the explorer following error occurs:
```
Traceback (most recent call last):
  File "/home/lucas/.local/lib/python3.6/site-packages/gcMapExplorer/gui/browser.py", line 1469, in load_map_file
    self.add_new_ccmap_axes(filename)
  File "/home/lucas/.local/lib/python3.6/site-packages/gcMapExplorer/gui/browser.py", line 1239, in add_new_ccmap_axes
    ax.set_aspect('equal', 'box-forced')
  File "/home/lucas/.local/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 1295, in set_aspect
    self.set_adjustable(adjustable, share=share)  # Handle sharing.
  File "/home/lucas/.local/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 1335, in set_adjustable
    cbook._check_in_list(["box", "datalim"], adjustable=adjustable)
  File "/home/lucas/.local/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 2164, in _check_in_list
    .format(v, k, ', '.join(map(repr, values))))
ValueError: 'box-forced' is not a valid value for adjustable; supported values are 'box', 'datalim'
```

In newer versions of matplotlib `box-forced` is deprecated (not sure which version). Now simply `box` should be used.